version: '3.5'

volumes:
  redis:

networks:
  supercache:
    driver: bridge

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - supercache
    volumes:
      - redis:/data